FROM ruby:2.3.0

USER root

ARG SECRET_KEY_BASE
ARG RAILS_ENV
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD

ENV SECRET_KEY_BASE=$SECRET_KEY_BASE
ENV RAILS_ENV=$RAILS_ENV
ENV RACK_ENV=$RAILS_ENV
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD

COPY Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install

ENV  APP_DIR /webapp/current

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
ADD . $APP_DIR

EXPOSE 80

CMD bundle exec puma -p 80
