FROM ruby:2.3.0

USER root

ARG SECRET_KEY_BASE
ARG RAILS_ENV
ARG DB_HOST
ARG DB_PORT
ARG POSTGRES_USERNAME
ARG POSTGRES_PASSWORD

ENV SECRET_KEY_BASE=$SECRET_KEY_BASE
ENV RAILS_ENV=$RAILS_ENV
ENV RACK_ENV=$RAILS_ENV
ENV DB_PORT_5432_TCP_ADDR=${DB_HOST:-localhost}
ENV DB_PORT_5432_TCP_PORT=${DB_PORT:-5432}
ENV POSTGRES_USERNAME=$POSTGRES_USERNAME
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

COPY Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install

ENV  APP_DIR /webapp/current

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
ADD . $APP_DIR

EXPOSE 80

CMD bundle exec puma -p 80
